version: "3"

services:
  uno-dev:
    build:
      context: .
      dockerfile: fe.dev.Dockerfile
    labels:
      # 设置Host 为 localhost 进行域名访问
      - traefik.http.routers.uno-dev.rule=Host(`dev.uno.merlin218.top`)
      # 开启HTTPS
      - traefik.http.routers.uno-dev.tls=true
      - traefik.http.routers.uno-dev.tls.certresolver=le
  server-dev:
    build:
      context: .
      dockerfile: end.Dockerfile
      # labels:
      # 设置Host 为 localhost 进行域名访问
      # - traefik.http.routers.uno-server.rule=Host(`uno.merlin218.top`)
      # 开启HTTPS
      # - traefik.http.routers.uno-server.tls=true
      # - traefik.http.routers.uno-server.tls.certresolver=le
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=uno
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "uno"
    volumes:
      - uno-mysql-data:/var/lib/mysql

volumes:
  uno-mysql-data:

networks:
  default:
    external:
      name: traefik_default
