name: uno

services:
  web:
    build:
      context: .
      dockerfile: fe.prod.Dockerfile
    restart: unless-stopped
    ports:
      - "30080:80"
    depends_on:
      - server
    networks:
      - 1panel-network

  server:
    build:
      context: .
      dockerfile: end.Dockerfile
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      UNO_PORT: 3000
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: uno
      MYSQL_USER: uno
    expose:
      - "3000"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
